#!/bin/sh
choice=$(printf "lock\nlogout\nsuspend\nreboot\nshutdown" | dmenu -i -p "Power:")

case "$choice" in
    lock)     slock ;;
    logout)   pkill -SIGTERM dwm ;;
    suspend)  slock & sleep 1 && systemctl suspend ;;
    reboot)   systemctl reboot ;;
    shutdown) systemctl poweroff ;;
esac
